#!/usr/bin/env bash
# contract-codegen: from rdb-schema.yaml scope={execution_specs,runner_results,rapid_crosscheck_requests,rapid_crosscheck_results,final_crosscheck_requests,hang_detections,audit_logs}
# 契約 relay-gate-db の生成物。手動編集禁止(再生成は bootstrap P4 / S3 のみ)。
# テーブル名・列名の定数。実装は必ずこの定数を経由して SQL を組み立てる。
# source 専用ライブラリのため未使用警告は対象外
# shellcheck disable=SC2034

# execution_specs: 起動時に解決済みのホスト・実行ユーザー・スクリプト・作業ディレクトリ・固定引数・追加引数・マップ版・実装版・hang_d
readonly TBL_EXECUTION_SPECS="execution_specs"
readonly COLS_EXECUTION_SPECS=(run_id parent_run_id job_id host exec_user script_path work_dir fixed_args additional_args job_map_version impl_version hang_detect_limit_minutes credential_ref)
readonly COL_EXECUTION_SPECS__RUN_ID="run_id"
readonly COL_EXECUTION_SPECS__PARENT_RUN_ID="parent_run_id"
readonly COL_EXECUTION_SPECS__JOB_ID="job_id"
readonly COL_EXECUTION_SPECS__HOST="host"
readonly COL_EXECUTION_SPECS__EXEC_USER="exec_user"
readonly COL_EXECUTION_SPECS__SCRIPT_PATH="script_path"
readonly COL_EXECUTION_SPECS__WORK_DIR="work_dir"
readonly COL_EXECUTION_SPECS__FIXED_ARGS="fixed_args"
readonly COL_EXECUTION_SPECS__ADDITIONAL_ARGS="additional_args"
readonly COL_EXECUTION_SPECS__JOB_MAP_VERSION="job_map_version"
readonly COL_EXECUTION_SPECS__IMPL_VERSION="impl_version"
readonly COL_EXECUTION_SPECS__HANG_DETECT_LIMIT_MINUTES="hang_detect_limit_minutes"
readonly COL_EXECUTION_SPECS__CREDENTIAL_REF="credential_ref"

# runner_results: blue/green runnerのforeground・background・rapid-crosscheck実行結果
readonly TBL_RUNNER_RESULTS="runner_results"
readonly COLS_RUNNER_RESULTS=(run_id slot_type role_type started_at stdout_path stderr_path exit_code status)
readonly COL_RUNNER_RESULTS__RUN_ID="run_id"
readonly COL_RUNNER_RESULTS__SLOT_TYPE="slot_type"
readonly COL_RUNNER_RESULTS__ROLE_TYPE="role_type"
readonly COL_RUNNER_RESULTS__STARTED_AT="started_at"
readonly COL_RUNNER_RESULTS__STDOUT_PATH="stdout_path"
readonly COL_RUNNER_RESULTS__STDERR_PATH="stderr_path"
readonly COL_RUNNER_RESULTS__EXIT_CODE="exit_code"
readonly COL_RUNNER_RESULTS__STATUS="status"

# rapid_crosscheck_requests: blueとgreenの完了通知を受けて作成する、ジョブ単位で非同期に行う速報クロスチェックの比較実行依頼。run_idで
readonly TBL_RAPID_CROSSCHECK_REQUESTS="rapid_crosscheck_requests"
readonly COLS_RAPID_CROSSCHECK_REQUESTS=(run_id job_id blue_run_id green_run_id requested_at status lease_expires_at worker_id)
readonly COL_RAPID_CROSSCHECK_REQUESTS__RUN_ID="run_id"
readonly COL_RAPID_CROSSCHECK_REQUESTS__JOB_ID="job_id"
readonly COL_RAPID_CROSSCHECK_REQUESTS__BLUE_RUN_ID="blue_run_id"
readonly COL_RAPID_CROSSCHECK_REQUESTS__GREEN_RUN_ID="green_run_id"
readonly COL_RAPID_CROSSCHECK_REQUESTS__REQUESTED_AT="requested_at"
readonly COL_RAPID_CROSSCHECK_REQUESTS__STATUS="status"
readonly COL_RAPID_CROSSCHECK_REQUESTS__LEASE_EXPIRES_AT="lease_expires_at"
readonly COL_RAPID_CROSSCHECK_REQUESTS__WORKER_ID="worker_id"

# rapid_crosscheck_results: 速報クロスチェックの比較結果を保持し、hang-detectorによる速報クロスチェック異常の検知・運用者への通知に用い
readonly TBL_RAPID_CROSSCHECK_RESULTS="rapid_crosscheck_results"
readonly COLS_RAPID_CROSSCHECK_RESULTS=(run_id comparison_result diff_count diff_detail_uri completed_at)
readonly COL_RAPID_CROSSCHECK_RESULTS__RUN_ID="run_id"
readonly COL_RAPID_CROSSCHECK_RESULTS__COMPARISON_RESULT="comparison_result"
readonly COL_RAPID_CROSSCHECK_RESULTS__DIFF_COUNT="diff_count"
readonly COL_RAPID_CROSSCHECK_RESULTS__DIFF_DETAIL_URI="diff_detail_uri"
readonly COL_RAPID_CROSSCHECK_RESULTS__COMPLETED_AT="completed_at"

# final_crosscheck_requests: 日次で全テーブル・全ファイルを対象に行う確報クロスチェックの比較実行依頼。速報側のエンティティと独立してrun_idで相
readonly TBL_FINAL_CROSSCHECK_REQUESTS="final_crosscheck_requests"
readonly COLS_FINAL_CROSSCHECK_REQUESTS=(run_id target_date status lease_expires_at worker_id target_tables target_files completed_at)
readonly COL_FINAL_CROSSCHECK_REQUESTS__RUN_ID="run_id"
readonly COL_FINAL_CROSSCHECK_REQUESTS__TARGET_DATE="target_date"
readonly COL_FINAL_CROSSCHECK_REQUESTS__STATUS="status"
readonly COL_FINAL_CROSSCHECK_REQUESTS__LEASE_EXPIRES_AT="lease_expires_at"
readonly COL_FINAL_CROSSCHECK_REQUESTS__WORKER_ID="worker_id"
readonly COL_FINAL_CROSSCHECK_REQUESTS__TARGET_TABLES="target_tables"
readonly COL_FINAL_CROSSCHECK_REQUESTS__TARGET_FILES="target_files"
readonly COL_FINAL_CROSSCHECK_REQUESTS__COMPLETED_AT="completed_at"

# hang_detections: background実行の未完了超過（ハング疑い）・非0終了エラー・速報クロスチェック異常を記録し、定期的な監視と運用者
readonly TBL_HANG_DETECTIONS="hang_detections"
readonly COLS_HANG_DETECTIONS=(detection_id run_id detection_type detected_at threshold_minutes slot_type notify_target resolved_at notified_at)
readonly COL_HANG_DETECTIONS__DETECTION_ID="detection_id"
readonly COL_HANG_DETECTIONS__RUN_ID="run_id"
readonly COL_HANG_DETECTIONS__DETECTION_TYPE="detection_type"
readonly COL_HANG_DETECTIONS__DETECTED_AT="detected_at"
readonly COL_HANG_DETECTIONS__THRESHOLD_MINUTES="threshold_minutes"
readonly COL_HANG_DETECTIONS__SLOT_TYPE="slot_type"
readonly COL_HANG_DETECTIONS__NOTIFY_TARGET="notify_target"
readonly COL_HANG_DETECTIONS__RESOLVED_AT="resolved_at"
readonly COL_HANG_DETECTIONS__NOTIFIED_AT="notified_at"

# audit_logs: リラン・中止（abort/abort_confirm）等、運用者による重要操作の監査証跡を記録する。RDRA情報モデルに
readonly TBL_AUDIT_LOGS="audit_logs"
readonly COLS_AUDIT_LOGS=(log_id operator operated_at run_id action)
readonly COL_AUDIT_LOGS__LOG_ID="log_id"
readonly COL_AUDIT_LOGS__OPERATOR="operator"
readonly COL_AUDIT_LOGS__OPERATED_AT="operated_at"
readonly COL_AUDIT_LOGS__RUN_ID="run_id"
readonly COL_AUDIT_LOGS__ACTION="action"
